### PR TITLE
Issue 249 nodetool info data

### LINKED ISSUE #249: Status Module to fetch relevant `nodetool info` data
Output of the `nodetool info`:

```
[user@host ~]$ nodetool info
ID                     : bb01d0a8-bcf3-4f16-82fc-7706a8929497
Gossip active          : true
Thrift active          : false
Native Transport active: true
Load                   : 170.03 GB
Generation No          : 1491893948
Uptime (seconds)       : 1386974
Heap Memory (MB)       : 12526.55 / 14956.00
Off Heap Memory (MB)   : 686.45
Data Center            : eu-west
Rack                   : 1c
Exceptions             : 2
Key Cache              : entries 24339595, size 1.99 GB, capacity 2 GB, 692137861 hits, 864143966 requests, 0.801 recent hit rate, 0 save period in seconds
Row Cache              : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, NaN recent hit rate, 0 save period in seconds
Counter Cache          : entries 0, size 0 bytes, capacity 50 MB, 0 hits, 0 requests, NaN recent hit rate, 7200 save period in seconds
Token                  : (invoke with -T/--tokens to see all 256 tokens)
```

Status module should fetch:

- Gossip active
- Thrift active
- Native Transport active
- Uptime (seconds) (in order to catch restarts)
- Key Cache 
- Row Cache
- Counter Cache

### PR DESCRIPTION
**Pull request by milannister**
This does NOT close #249  entirely. Only active native transport info is currently implemented.

### CODE REVIEW

File: cassandra-diagnostics-connector30/src/main/java/io/smartcat/cassandra/diagnostics/connector/NodeProbeWrapper.java [hunk 1]
```diff
@@ -118,4 +118,14 @@ public long getRepairSessions() {
         return unreachableNodes;
     }
 
+    /**
+     * Get the information if the native transport is active on the node.
+     *
+     * @return true iff native transport is active
+     */
+    @Override
+    public boolean getNativeTransportActive() {
```
Comment (mgobec) [inline cassandra-diagnostics-connector30/src/main/java/io/smartcat/cassandra/diagnostics/connector/NodeProbeWrapper.java]: Instead of providing a boolean for this value can this be wrapped into a class like nodeinfo or something that will have all the fields reported by nodetool info?

**Comment by mgobec** [comment]
I vote to postpone this PR until everything is implemented

**Review by milannister — COMMENTED** [review]
- Add functional test (FTBasic)
- Update readme.md for status module

File: cassandra-diagnostics-core/src/main/java/io/smartcat/cassandra/diagnostics/module/status/StatusModule.java [hunk 2]
```diff
@@ -66,6 +71,7 @@ public StatusModule(ModuleConfiguration configuration, List<Reporter> reporters,
         compactionsEnabled = config.compactionsEnabled();
         tpStatsEnabled = config.tpStatsEnabled();
         repairsEnabled = config.repairsEnabled();
+        nativeTransportActiveEnabled = config.nodeInfoEnabled();
```
Comment (nbozic-zz) [inline cassandra-diagnostics-core/src/main/java/io/smartcat/cassandra/diagnostics/module/status/StatusModule.java]: Rename variable to be `nodeInfoEnabled` and not `nativeTransportActiveEnabled`

**Review by nbozic-zz — COMMENTED** [review]
Change readme and add testing if log line with nodetool info exists in FTBasic test (functional test).

**Review by nbozic-zz — APPROVED** [review]
