### PR TITLE
Improving functional tests and fixing some bugs:

### LINKED ISSUE #213: Extend functional tests to include tracing
Extend the diagnostics functional tests (basic) to cover the statement tracing feature.

### PR DESCRIPTION
**Pull request by nbozic-zz**
- be explicite, when enable tracing is false do not log statement even when
it is String query (not prepared statement)
- make core modules readme consistent
- add tracing functional test which is checking both types of statements (
prepared and plain String) and compares log output against sent statement
- cover all modules in basic test
- remove system log for Cassandra after test since it is never deleted and
it makes tests pass even if last log is wrong

Fixes #213

### CODE REVIEW

File: cassandra-diagnostics-ft/src/functional-test/java/io/smartcat/cassandra/diagnostics/ft/basic/FTBasic.java [hunk 1]
```diff
@@ -36,43 +48,94 @@ public static void setUp() throws ConfigurationException, TTransportException, I
...
+            }
+        }
+        reader.close();
+
+        Assertions.assertThat(queryReportFound).isTrue();
+        Assertions.assertThat(queryCountFound).isTrue();
+        Assertions.assertThat(heartbeatFound).isTrue();
+        Assertions.assertThat(requestRateFound).isTrue();
+        Assertions.assertThat(repairSessionsFound).isTrue();
+        Assertions.assertThat(repairSessionsFound).isTrue();
```
Comment (nivancevic) [inline cassandra-diagnostics-ft/src/functional-test/java/io/smartcat/cassandra/diagnostics/ft/basic/FTBasic.java]: compactionInfoFound instead of repairSessionsFound

**Review by nivancevic — CHANGES_REQUESTED** [review]
